### ISSUE TITLE
Slow during recording, toDataUrl() too slow?

### ISSUE THREAD

**Issue by pathammer** [thenickdude/webm-writer-js#10]
I'm seeing my animation loop go from 60fps to 15-8 fps when I begin recording. It runs a little bit faster when I set the quality lower. I'm trying to record a canvas approx 1280x720

My animation loop runs smoothly when I use the MediaReording API so I know my system can encode video fast enough.

When I profile the code, it's spending 70-80ms in toDataUrl()

Is there any trick to get this to run faster?

**Comment by thenickdude** [comment]
toDataUrl is Chrome's WebP encoder running, so it can't really be sped up.
