### ISSUE TITLE
webm header implementation

### ISSUE THREAD

**Issue by Edqe14** [thenickdude/webm-writer-js#24]
Hello,
I'm currently working on live transcoding and one of the formats is audio only `webm` using `opus` encoding. It can't be played on browser nor a media player and I figured out that it's missing a header. I found this repo and checked the source and found a function which builds/write the header.

Can you explain to me how it works? or how can I create my own implementation for it?

Much thanks!

**Comment by thenickdude** [comment]
https://www.webmproject.org/docs/container/

https://www.matroska.org/technical/basics.html

https://github.com/ietf-wg-cellar/ebml-specification/blob/master/specification.markdown

**Comment by trackedsupport** [comment]
I am having a similar issue. How can I build/write the header?
