### ISSUE TITLE
New version release

### ISSUE THREAD

**Issue by ilijapuaca** [thenickdude/webm-writer-js#36]
It would be much appreciated if a new release could be cut in order to include https://github.com/thenickdude/webm-writer-js/pull/17 which has now landed, and is one of the blockers for us continuing to make use of the library

**Comment by thenickdude** [comment]
It took me a long time to work out how to rework the Electron example to work with modern versions of Electron! (I haven't used that for years)

I've updated that now and published 1.0.0 to NPM, please check it out for me

**Comment by ilijapuaca** [comment]
Thanks for taking care of this! Will check it out, I'll close the issue since release is out
