### ISSUE TITLE
my webm videos are really big,why?(26 MB for a 10 second animation) 

### ISSUE THREAD

**Issue by kapooky** [thenickdude/webm-writer-js#9]
Hello, Does anyone else have the same problem as me?

Background info:
-The videos were rendered at 60fps,1920x1080, and at the lowest possible quality setting. 
-I am using CCapture,a library for replaying canvas based animations. It uses this project for webm video rendering. (Perhaps CCapture is the culprit)

**Comment by thenickdude** [comment]
That sounds about right, what resolution are your videos? This project only
supports keyframes so it's basically just a series of JPEG-equivalents.

In an earlier version of this project there was a bug where the quality
option did nothing - does your filesize change when you change the quality
parameter?

**Comment by thenickdude** [comment]
Ah yep it looks like CCapture uses 0.2.0, where the quality setting is non-functional. Try replacing that with https://github.com/thenickdude/webm-writer-js/releases/tag/v0.2.4

**Comment by kapooky** [comment]
thanks, I'll swap the versions soon and report back the results. 

Playing around with the webm quality had a minor effect on file size. The file size shrunk by 7% when switching from highest to lowest quality setting.

**Comment by kapooky** [comment]
Swapping out to the newest version of webmwriter reduced file size from 26mb(highest quality) to 11mb!(at 10 percent quality)

**Comment by thenickdude** [comment]
Thanks for the test, I'll submit a pull request to them to get it updated.
